version: 1.0.5

image:
  - Visual Studio 2020
  - Ubuntu

platform:
  - x64

configuration:

branches:
  only:
    - main

build:
  parallel: true
  publish_wap: true
  publish_wap_xcopy: true
  publish_wap_beanstalk: true
  publish_wap_octopus: true
  publish_azure_webjob: true
  publish_azure: true
  publish_aspnet_core: true
  publish_core_console: true
  publish_nuget: true
  publish_nuget_symbols: true
  include_nuget_references: true
