version: '3'

services:
  vodskipper:
    image: thnderbread/vodskipper:vodskipper-test
    privileged: true
    tty: true
    volumes:
      - ./tests:/app/.tests
container:
  options: --shm-size=2gb

    # all that's left is to try splitting mocks and tests
    # and to try publishing the extension
    