name: "Test"
on: # rebuild any PRs and main branch changes
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Install
        run: npm ci

      - name: Download Chrome Stable
        run: |
          wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | \
          sudo gpg --no-default-keyring --keyring gnupg-ring:/etc/apt/trusted.gpg.d/google.gpg --import; \
          sudo chmod 644 /etc/apt/trusted.gpg.d/google.gpg; \
          echo "deb https://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list; \
          sudo apt-get update -y; \
          sudo apt-get install -y google-chrome-stable;

      - name: Download ChromeDriver
        run: |
          CHROMEDRIVER_VERSION=$(curl https://googlechromelabs.github.io/chrome-for-testing/LATEST_RELEASE_STABLE); \
          sudo wget -N https://storage.googleapis.com/chrome-for-testing-public/$CHROMEDRIVER_VERSION/linux64/chromedriver-linux64.zip -P ~/ && \
          sudo unzip ~/chromedriver-linux64.zip -d ~/ && \
          sudo rm ~/chromedriver-linux64.zip && \
          sudo mv -f ~/chromedriver-linux64/chromedriver /usr/bin/chromedriver && \
          sudo rm -rf ~/chromedriver-linux64

        env:
          CHROME_BINARY: /usr/bin/google-chrome
          DRIVER_BINARY: /usr/bin/chromedriver

      - name: Bundle
        run: npm run bundle-dev

      - name: Test
        run: npm run test

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: Screenshot & logs
          path: |
            ./screenshot.png
            ./wdio-chromedriver.log

      - uses: actions/upload-artifact@v3
        with:
          name: extension-files
          path: |
            ./*.crx
            ./*.zip
