name: "Test"
on: # rebuild any PRs and main branch changes
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:stable
        options: >-
          --privileged
          --shm-size=2gb

    steps:
      - name: Checkout Github Repo
        uses: actions/checkout@v4

      # - name: Run Docker Compose
      #   run: docker-compose up

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: thnderbread/vodskipper:vstest-latest

      - uses: hoverkraft-tech/compose-action@v1.5.1

      # - name: Build Docker image
      #   run: docker build -t vodskipper-test .

      # - name: Start Docker container test run
      #   run: docker run --name vs-container vodskipper-test

      # - uses: actions/setup-node@v4
      #   with:
      #     node-version: 20

      # - run: npm ci

      # - run: npm run bundle-dev

      # - run: npm run test-ci

      # - uses: actions/upload-artifact@v4
      #   if: always()
      #   with:
      #     name: info.txt
      #     path: ./info.txt
