name: "Test"
on: # rebuild any PRs and main branch changes
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:stable
        options: |
          --privileged
          --shm-size=2gb

    steps:
      - name: Checkout Github Repo
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t vodskipper-test .

      - name: Start Docker container test run
        run: docker run vodskipper-test
