name: "Test"
on: # rebuild any PRs and main branch changes
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Install
        run: npm ci

      - name: Bundle
        run: npm run bundle-dev

      - name: Install Xvfb & ffmpeg
        run: sudo apt-get update && sudo apt-get install -y xvfb ffmpeg

      - name: Start Xvfb
        run: |
          Xvfb :99 -screen 0 1920x1080x24 &
          export DISPLAY=:99

      - name: Test
        run: |
          DISPLAY=:99 ffmpeg -video_size 1920x1080 -framerate 30 -f x11grab -i :99 -c:v libx264 -preset ultrafast -tune zerolatency -crf 18 output.mp4 &
          npm run test-ci
          pkill ffmpeg

      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: Screen-Recording
          path: output.mp4

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: Screenshot & logs
          path: |
            ./screenshot.png
            ./wdio-chromedriver.log

      - uses: actions/upload-artifact@v3
        with:
          name: extension-files
          path: |
            ./*.crx
            ./*.zip
