name: "Test"
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3
      - name: Build Docker image
        run: docker build -t vodskipper:0.0.1 .
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: vodskipper-image:0.0.1

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3
      - name: Install
        run: npm ci
      - name: Test
        run: npm run test
      - uses: actions/upload-artifact@v3
        with:
          name: extension-files
          path: |
            ./*.crx
            ./*.zip
