name: "Test"
on: # rebuild any PRs and main branch changes
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: windows-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Install
        run: npm ci

      - name: Bundle
        run: npm run bundle-dev

      - name: Test
        run: npm run test

      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: Screenshot
          path: ./screenshot.png

      - uses: actions/upload-artifact@v3
        with:
          name: extension-files
          path: |
            ./*.crx
            ./*.zip
