name: "Test"
on: # rebuild any PRs and main branch changes
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Install
        run: npm ci

      - name: Bundle
        run: npm run bundle-dev

      - name: Install ffmpeg
        run: sudo apt-get update && sudo apt-get install -y ffmpeg

      - name: Start Recording
        run: ffmpeg -video_size 1920x1080 -framerate 30 -f x11grab -i :0.0 -c:v libx264 -preset ultrafast -tune zerolatency -crf 18 output.mp4 &

      - name: Test
        run: npm run test

      - name: Stop Recording
        run: pkill ffmpeg

      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: Screen-Recording
          path: output.mp4

      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: Screenshot
          path: ./screenshot.png

      - uses: actions/upload-artifact@v3
        with:
          name: extension-files
          path: |
            ./*.crx
            ./*.zip
